services:
  app:
    build:
      context: ${DEV_BUILD_CONTEXT}/oer-finder-plugin
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - .:/home/node/app
      - ${DEV_BUILD_CONTEXT}/oer-finder-plugin/.claude:/home/node/app/.claude